### ISSUE TITLE
typeerror from clamp

### ISSUE THREAD

**Issue by ghost** [DeltaNeverUsed/reddit-place-script-2022#12]
```
Traceback (most recent call last):
  File "D:\David\Documents\RPlace\reddit-place-script-2022-Delta-s-Edition-main\main.py", line 505, in <module>
    time.sleep(clamp(pixel_place_frequency/len(accounts))+1-time_taken, 1, 99999999)
TypeError: clamp() missing 2 required positional arguments: 'a' and 'b'
```

**Comment by ghost** [comment]
oh also
```
{"errors":[{"message":"'Y' has to be within 0-999 range","path":["act"]}],"data":null}
that's probably not good 1 error(s)
```

**Comment by DeltaNeverUsed** [comment]
should work now.

**Comment by DeltaNeverUsed** [comment]
> ```
> Traceback (most recent call last):
>   File "D:\David\Documents\RPlace\reddit-place-script-2022-Delta-s-Edition-main\main.py", line 505, in <module>
>     time.sleep(clamp(pixel_place_frequency/len(accounts))+1-time_taken, 1, 99999999)
> TypeError: clamp() missing 2 required positional arguments: 'a' and 'b'
> ```

forgot to fix this.
is now also fixed

**Comment by botcoder-sys** [comment]
> should work now.
@DeltaNeverUsed 
Still not working 
reddit-place-script-2022-main\main.py", line 508, in <module>
    time.sleep(clamp(pixel_place_frequency/len(accounts))+1-time_taken, 1, 99999999)
TypeError: clamp() missing 2 required positional arguments: 'a' and 'b'

**Comment by ghost** [comment]
```
placing pixel
Sending: POST https://gql-realtime-2.reddit.com/query
{"errors":[{"message":"Ratelimited","path":["act"],"extensions":{"nextAvailablePixelTs":1649015989000}},{"message":"ratelimit hit, next available: 1649015989000","path":["act"]}],"data":null}
that's probably not good 1 error(s)
next pixel in -200.0 seconds
Response status: 200
Traceback (most recent call last):
  File "D:\David\Documents\RPlace\reddit-place-script-2022-Delta-s-Edition-main\main.py", line 508, in <module>
    time.sleep(clamp(pixel_place_frequency/len(accounts))+1-time_taken, 1, 99999999)
TypeError: clamp() missing 2 required positional arguments: 'a' and 'b'
Image Progress: |████████████████----------------------------------| 32.9% Complete

Account Progress: |██------------------------------------------------| 5.0% End


Process finished with exit code 1
```

**Comment by ghost** [comment]
idk if that helps

**Comment by DeltaNeverUsed** [comment]
works on my end, are you sure you have the newest version?
